/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkCategoryIndexRouteImport } from './routes/work.$category.index'
import { Route as WorkCategorySlugRouteImport } from './routes/work.$category.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCategoryIndexRoute = WorkCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCategorySlugRoute = WorkCategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/': typeof WorkIndexRoute
  '/work/$category/$slug': typeof WorkCategorySlugRoute
  '/work/$category/': typeof WorkCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkIndexRoute
  '/work/$category/$slug': typeof WorkCategorySlugRoute
  '/work/$category': typeof WorkCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/': typeof WorkIndexRoute
  '/work/$category/$slug': typeof WorkCategorySlugRoute
  '/work/$category/': typeof WorkCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/work/'
    | '/work/$category/$slug'
    | '/work/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/work/$category/$slug'
    | '/work/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/work/'
    | '/work/$category/$slug'
    | '/work/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$category/': {
      id: '/work/$category/'
      path: '/$category'
      fullPath: '/work/$category/'
      preLoaderRoute: typeof WorkCategoryIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$category/$slug': {
      id: '/work/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/work/$category/$slug'
      preLoaderRoute: typeof WorkCategorySlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkIndexRoute: typeof WorkIndexRoute
  WorkCategorySlugRoute: typeof WorkCategorySlugRoute
  WorkCategoryIndexRoute: typeof WorkCategoryIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkIndexRoute: WorkIndexRoute,
  WorkCategorySlugRoute: WorkCategorySlugRoute,
  WorkCategoryIndexRoute: WorkCategoryIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
